// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpgHASOlFOU_FjZIiYXrZihrJbgJiga48',
    appId: '1:278267049549:web:9d8aaea2fb14358ef74e04',
    messagingSenderId: '278267049549',
    projectId: 'veloura-321',
    authDomain: 'veloura-321.firebaseapp.com',
    storageBucket: 'veloura-321.firebasestorage.app',
    measurementId: 'G-Z6MXJCKKFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQPU_Re-FqkrssdVb-OR8x6oioh0UwIio',
    appId: '1:278267049549:android:2350b0af1df8c29ef74e04',
    messagingSenderId: '278267049549',
    projectId: 'veloura-321',
    storageBucket: 'veloura-321.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcIDNhxdjrM918DxNwsLn_3vBGoFh6VcM',
    appId: '1:278267049549:ios:07fd6ac470572dc0f74e04',
    messagingSenderId: '278267049549',
    projectId: 'veloura-321',
    storageBucket: 'veloura-321.firebasestorage.app',
    iosBundleId: 'com.example.veloura',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcIDNhxdjrM918DxNwsLn_3vBGoFh6VcM',
    appId: '1:278267049549:ios:07fd6ac470572dc0f74e04',
    messagingSenderId: '278267049549',
    projectId: 'veloura-321',
    storageBucket: 'veloura-321.firebasestorage.app',
    iosBundleId: 'com.example.veloura',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpgHASOlFOU_FjZIiYXrZihrJbgJiga48',
    appId: '1:278267049549:web:5a82a01731345f7af74e04',
    messagingSenderId: '278267049549',
    projectId: 'veloura-321',
    authDomain: 'veloura-321.firebaseapp.com',
    storageBucket: 'veloura-321.firebasestorage.app',
    measurementId: 'G-S4MMW1RQW0',
  );
}
